# Generated by Django 5.1.2 on 2024-10-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
