# Generated by Django 5.1.2 on 2024-10-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mates_points',
            field=models.IntegerField(null=True),
        ),
    ]
