# Generated by Django 5.1.2 on 2024-10-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_mates_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mates_points',
            field=models.IntegerField(default=0),
        ),
    ]
