# Generated by Django 5.1.2 on 2024-11-05 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_mates_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='ui',
            new_name='uid',
        ),
    ]
